-- Deprecated monolithic schema. Apply per-database schemas instead:
--
--   psql auth_db     -f database/auth_db/schema.sql
--   psql business_db -f database/business_db/schema.sql
--   psql rag_db      -f database/rag_db/schema.sql
