-- Deprecated monolithic seed. Apply per-database seeds instead:
--
--   psql auth_db     -f database/auth_db/seed.sql
--   psql business_db -f database/business_db/seed.sql
--   psql rag_db      -f database/rag_db/seed.sql
--
-- Then ingest RAG PDFs:
--   cd backend/rag-service && python -m app.seeders.knowledge_seeder
